/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_RESIZER_IMAGE__
#define __RUST_RESIZER_IMAGE__

#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

uint8_t * resize_image (
    int8_t const * base64_data,
    uint32_t width,
    uint32_t height);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __RUST_RESIZER_IMAGE__ */
