// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.32.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Uint8List> resizer(
        {required String image,
        required int width,
        required int height,
        required int percent,
        dynamic hint}) =>
    RustLib.instance.api.resizer(
        image: image,
        width: width,
        height: height,
        percent: percent,
        hint: hint);
